---
- name: remove all current configuration files
  shell: rm -rf /etc/nginx/

- name: copy nginx folder to /etc/nginx
  copy:
    src: etc/nginx/
    dest: /etc/nginx/

- name: symlink modules directory
  shell: ln -s /usr/lib/nginx/modules /etc/nginx/modules

- name: template nginx.conf to /etc/nginx/nginx.conf
  template: 
    src: etc/nginx/nginx.conf 
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: template default.conf to /etc/nginx/conf.d/default.conf
  template: 
    src: etc/nginx/conf.d/default.conf 
    dest: /etc/nginx/conf.d/default.conf
  notify: restart nginx
