---
- name: create backup directory
  file:
    path: /var/backups
    state: directory
    mode: 0755

- name: backup /etc/nginx/ folder
  shell: cp -a /etc/nginx /var/backups/nginx-conf-backup-$(date +%s | sha256sum | base64 | head -c 32 ; echo)
  ignore_errors: yes

- name: backup /etc/nginx/ folder
  shell: cp -a /var/log/nginx /var/backups/nginx-log-backup-$(date +%s | sha256sum | base64 | head -c 32 ; echo)
  ignore_errors: yes

