---
- name: create SSL directory
  file: 
    path: /etc/ssl/nginx
    state: directory

- name: install nginx signing key
  apt_key: 
    url: http://nginx.org/keys/nginx_signing.key
    state: present

- name: copy the NGINX Plus cert and key
  copy: 
    src: etc/ssl/nginx/ 
    dest: /etc/ssl/nginx/

- name: download sources.list.d for NGINX Plus on current version
  shell: printf "deb https://plus-pkgs.nginx.com/ubuntu `lsb_release -cs` nginx-plus\n" | sudo tee /etc/apt/sources.list.d/nginx-plus.list

- name: download apt configuration
  get_url: url=https://cs.nginx.com/static/files/90nginx dest=/etc/apt/apt.conf.d/90nginx mode=0700

- name: update apt cache
  apt:
    update_cache: yes

- name: install nginx plus
  apt: 
    name: nginx-plus 
    state: present
  notify: start nginx
