---
- name: install nginx plus
  apt: name=nginx-plus state=present

- name: copy nginx configuration
  template: src=etc/nginx/conf.d/default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
