---
- name: backup /etc/nginx/ folder
  shell: cp -a /etc/nginx /etc/nginx-backup-$(date +%s | sha256sum | base64 | head -c 32 ; echo)
  ignore_errors: yes

- name: backup /etc/nginx/ folder
  shell: cp -a /var/log/nginx /var/log/nginx-backup-$(date +%s | sha256sum | base64 | head -c 32 ; echo)
  ignore_errors: yes

- name: install apt-transport-https
  apt: 
    name: apt-transport-https 
    state: present

- name: install lsb-release
  apt: 
    name: lsb-release 
    state: present

- name: install ca-certificates
  apt: 
    name: ca-certificates 
    state: present

#- name: install pre-reqs here
#- name: install pre-reqs here
#  apt: name=package_here state=present
